### PR TITLE
[HHQ-4561] Allow selective access to system roles in HQApi

### PR DESCRIPTION
**Pull request by wjs-broadcom**
Ryan,

Here's the changes for HHQ-4561

### CODE REVIEW

**Comment by wjs-broadcom** [comment]
Ryan,

Fixed and added

**Comment by rmorgan** [comment]
Wes,

I was hoping for a bit more coverage in the tests.  Can you add tests for the following:

1) Test to rename the super user role (asserting it cannot be changed)
2) Test changing users of super user role (as admin)
3) Test changing users of super user role (as non-admin)

Guessing we should add the same for the guest role?

**Comment by wjs-broadcom** [comment]
Ryan,

Added tests and implemented a workaround for lack of permission checking in the backend. Removed the stray code. I figured out why it was so garbled. I had a power outage and my editor did an auto save/recover and I didn't realize it. So it should be good now.

**Comment by wjs-broadcom** [comment]
Ryan

Added the missing break

**Pull request merged**
